### Register a new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Meznah",
  "email": "meznah@example.com",
  "password": "123456"
}



### Login existing user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "meznah@example.com",
  "password": "123456"
}

### Get logged-in user info (protected)
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MmQzNzExZDQ4ZjM0YThjMTI2OWZjYiIsImlhdCI6MTc2NDYxNjk5MywiZXhwIjoxNzY3MjA4OTkzfQ.H5gUdbr5o4dihlQiJeyLP19od8Mzw2oqBYx7mE0o_XQ

